version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet
    steps:
      - checkout
      - run: dotnet build      
      - run: dotnet test /api-core-app-test/api-core-app-test.csproj
      

